# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_ai',
                'doc_host': 'https://drbhatti.github.io',
                'git_url': 'https://github.com/drbhatti/nbdev_ai',
                'lib_path': 'nbdev_ai'},
  'syms': {'nbdev_ai.core': {'nbdev_ai.core.foo': ('core.html#foo', 'nbdev_ai/core.py')}}}
